---
# Install Apache HTTPD server as a reverse proxy
- hosts: all
  become: yes
  vars:
    vhost_server_name: erp-dev.example.edu
    vhost_doc_root: "/var/www/html"
    vhost_port_http: 80
    tomcat_port_ajp: 8010
    
  tasks:
    - name: install apache2
      yum: 
        name: httpd 
        state: present

    # - name: enabled mod_rewrite
    #   apache2_module: name=rewrite state=present
    #   notify:
    #     - restart httpd
    
#    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
#      seboolean:
#        name: httpd_can_network_connect
#        state: yes
#        persistent: yes

    - name: Create doc root "{{ vhost_doc_root }}"
      file:
        path: "{{ vhost_doc_root }}"
        state: directory
        #mode: '0744'

    # - name: Copy SSL Cert Key
    #   copy:
    #     src: certs/ssb-tst3.uco.edu.key
    #     dest: "{{vhost_ssl_cert_key_file}}"
    #     owner: root
    #     group: root
    #     mode: '0644'
        
    # - name: Copy SSL Cert File
    #   copy:
    #     src: certs/ssb-tst3_uco_edu_cert.cer
    #     dest: "{{vhost_ssl_cert_file}}"
    #     owner: root
    #     group: root
    #     mode: '0644'
        
    - name: Configure Virtual Host file
      template:
        src: "templates/{{ vhost_server_name }}.conf.j2"
        dest: "/etc/httpd/conf.d/{{ vhost_server_name }}.conf"
        backup: yes
      tags:
        - "configuration"  
      notify:
        - restart httpd
    
    - name: insert firewalld rule for apache http port 80
      tags:
      - "configuration"  
      firewalld: port=80/tcp permanent=yes state=enabled immediate=yes
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
      ignore_errors: true

  handlers:
    - name: restart httpd
      service: 
        name: httpd 
        state: restarted