---
# ---
# - hosts: all
#   become: yes
#   become_method: sudo
#   tasks:
#  - name: Update OS
#    package:
#     name: '*'
#     state: latest
- hosts: all
  become: yes
  tasks:
    - name: create vagrant2 group
      group: name=vagrant2 state=present
    - name: create vagrant2 user
      user: name=vagrant2 group=vagrant2 state=present
    - name: create .ssh directory for vagrant user
      file: >
        path=/home/vagrant2/.ssh
        state=directory
        owner=vagrant2
        group=vagrant2
        mode=0700
    - name: add authorized_keys for vagrant user
      authorized_key: user=vagrant2 key="{{ item }}"
      with_file:
        - "{{ lookup('env', 'HOME') }}/.ssh/vagrant2.pub"

    - name: check vagrant is in sudoers
      shell: grep -q ^vagrant2 /etc/sudoers; echo $?
      register: result
    - name: add vagrant2 user to sudoers
      shell: |
        echo "vagrant2 ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
      when: result.stdout != "0"

    - name: Generate /etc/hosts file
      template:
        src: hosts_template.j2
        dest: /etc/hosts