---
# Configures Tomcat for use with Banner 9 Apps
# Source: https://ellucian.force.com/clients/s/article/Suggestions-for-app-server-performance-tuning-used-in-load-performance-testing
# Source: https://resources.elluciancloud.com/bundle/banner_appnav_acn_install_3.3.1/page/t_config_tomcat_serv.html

- hosts: tomcat
  become: yes
  gather_facts: no
  # vars_files:
  #   vars/tomcat_vars.yml
  #   vars/banner_vars.yml
  vars:
    tomcat_user: tomcat
    tomcat_group: tomcat
    tomcat_catalina_home: /u01/tomcat/latest #location of symlink to latest extracted Tomcat binaries
    tomcat_catalina_base: /u01/config/dev #location of Tomcat instance config and webapps
    extra_libs_files: ['files/ojdbc8.jar', 'files/xdb.jar']
    banner_setenv_template: templates/setenv.sh.j2

  tasks:
  - name: Copy extra libs files to "{{ tomcat_catalina_home }}/libs"
    copy:
      src: "{{ item }}"
      dest: "{{ tomcat_catalina_home }}/libs"
      force: no
    with_items:
      "{{ extra_libs_files }}"
  
  - name: Ensure {{ tomcat_catalina_base }}/bin exists
    file:
      path: "{{ tomcat_catalina_base }}/bin"
      state: directory
      mode: 0755
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"

  - name: Configure "{{ tomcat_catalina_base }}/bin/setenv.sh" from template "{{ banner_setenv_template }}"
    template:
      src: "{{ banner_setenv_template }}"
      dest: "{{ tomcat_catalina_base }}/bin/setenv.sh"
      mode: 0755
      owner: "{{ tomcat_user }}"
      group: "{{ tomcat_group }}"
