---
# Installs Tomcat 8

- hosts: tomcat
  become: yes
  gather_facts: no
  vars:
    tomcat_version: 8.5.58

  tasks:

  - name: Ensure instance group exists
    group:
      name: tomcat
      state: present

  - name: Ensure instance user exists
    user:
      name: tomcat
      state: present
      group: tomcat
      createhome: no
      system: yes

  - name: Create base /u01 directory
    file:
      path: /u01
      state: directory
      mode: 0755
      owner: tomcat
      group: tomcat

  - name: Create /u01/tomcat directory
    file:
      path: /u01/tomcat
      state: directory
      mode: 0755
      owner: tomcat
      group: tomcat

  - name: Install prerequisite software
    yum:
      name: ['java-1.8.0-openjdk', 'vim']
      state: present

  - name: Copy apache-tomcat-8.5.58.tar.gz Archive to /tmp/ on host server
    copy:
      src: apache-tomcat-8.5.58.tar.gz
      dest: /tmp/apache-tomcat-8.5.58.tar.gz

  # - name: Download Tomcat source
  #   get_url:
  #     url: https://archive.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
  #     dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
  #     mode: "440"

  - name: install tomcat instance
    unarchive:
      src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
      dest: /u01/tomcat
      owner: tomcat
      group: tomcat
      remote_src: yes
      extra_opts: ['--show-stored-names']
      mode: "0755"

  - name: Create a symbolic link
    file:
      src: /u01/tomcat/apache-tomcat-{{ tomcat_version }}
      dest: /u01/tomcat/latest
      mode: 0755
      owner: tomcat
      group: tomcat
      state: link

  - name: Create /u01/config/instance1 directory
    file:
      path: /u01/config/instance1
      state: directory
      mode: 0755
      owner: tomcat
      group: tomcat

  - name: Seed conf from src
    copy:
      src: /u01/tomcat/latest/conf
      dest: /u01/config/instance1
      owner: tomcat
      group: tomcat
      mode: preserve
      remote_src: yes
      force: no
      follow: yes

  - name: Seed logs from src
    copy:
      src: /u01/tomcat/latest/logs
      dest: /u01/config/instance1
      owner: tomcat
      group: tomcat
      remote_src: yes
      follow: yes

  - name: Seed temp from src
    copy:
      src: /u01/tomcat/latest/temp
      dest: /u01/config/instance1
      owner: tomcat
      group: tomcat
      remote_src: yes
      force: no
      follow: yes

  - name: Seed webapps from src
    copy:
      src: /u01/tomcat/latest/webapps
      dest: /u01/config/instance1
      owner: tomcat
      group: tomcat
      remote_src: yes
      force: no
      follow: yes

  - name: Seed work from src
    copy:
      src: /u01/tomcat/latest/work
      dest: /u01/config/instance1
      owner: tomcat
      group: tomcat
      remote_src: yes
      follow: yes

  - name: Configure Tomcat Manager Users
    no_log: false
    template:
      src=tomcat-users.xml
      dest=/u01/config/instance1/conf/tomcat-users.xml
    notify: restart tomcat

  - name: Configure Tomcat service
    no_log: false
    template:
      src=tomcat.service
      dest=/etc/systemd/system/tomcat.service
    notify: restart tomcat

  # - name: insert firewalld rule for tomcat http port 8080
  #   tags:
  #   - "configuration"  
  #   firewalld: 
  #     port: 8080/tcp 
  #     permanent: yes 
  #     state: enabled 
  #     immediate: yes

  - name: Ensure Tomcat is running
    systemd:
      name: tomcat
      state: started
      daemon_reload: yes

  handlers:
    - name: restart tomcat
      systemd:
        name: tomcat
        state: restarted
        daemon_reload: yes
